[package]
name = "clientfuture"
version = "0.1.0"
authors = ["Jakob Gillich <jakob@gillich.me>"]
edition = "2018"

[dependencies]
juniper = "0.11.1"
juniper_warp ="0.2.0"
trust-dns = "0.15.1"
warp = "0.1.14"
tokio = "0.1.18"